---
title: "Defense"
editor: visual
execute: 
  echo: false
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(readxl)
library(writexl)
library(stringr)
library(rstanarm)
library(dplyr)
library(ggplot2)
library(plotly)
```

```{r}
#| echo: false
#| message: false
#| warning: false
# puts the data into a spreadsheet
ddata <- read.csv("mls-salaries-2007.csv")

```

### Plot for all defenders in MLS League in 2007

```{r}

#| echo: false
#| message: false
#| warning: false
# plots the data by filtering the position to be defense
# points are colored by club name
# plots a dotted line to represent the average salary for a defender
ddata |> 
  filter(position == "D") |> 
  select(position, base_salary, club, first_name, last_name) |>
  ggplot(mapping = aes(x = position, 
                       y = base_salary, 
                       color = club)) + 
  geom_jitter(size = 2.5) + 
  scale_y_continuous(labels=scales::dollar_format()) + 
    scale_color_discrete( 
    labels = c("CHI" = "Chicago Fire", "CHV" = "Chivas USA", "CLB" = "Columbus Crew", "COL" =         "Colorado Rapids", "DAL" = "FC Dallas", "DC" = "D.C. United", "HOU" = "Houston Dynamo", "KC" =     "Kansas City Wizards", "LA" = "LA Galaxy", "NE" = "New England Revolution", "NY" = "New York Red Bulls", "RSL" = "Real Salt Lake", "TFC" = "Toronto FC")) + 
  labs(title = "Soccer salaries earned for defensive players in 2007",
       subtitle = "Average salary for a defender is around $65,000 which is less than average for midfielders",
       x = "Position", 
       y = "Player Base Salary", 
       caption = "Source: Originally from MLS Union", 
       color = "Club") + 
  theme_classic() + 
  geom_hline(yintercept = 66842.51, linetype = "dashed", color = "red")


```

This data shows the spread of salaries for defenders in 2007. The colors show the clubs each player was in, and the spread is wider than some might think. The line in the middle of the graph displays the average for all defenders in the MLS League in 2007, which is \$66,842.51.
