---
title: "Midfield"
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(readxl)
library(writexl)
library(stringr)
library(rstanarm)
library(dplyr)
```

```{r}
#| echo: false
#| message: false
#| warning: false
mdata <- read.csv("mls-salaries-2007.csv")

```
### Plot for all midfelders in MLS League in 2007
```{r}
#| echo: false
#| message: false
#| warning: false
mdata |> 
  filter(position == "M") |> 
  select(position, base_salary, club, first_name, last_name) |>
  ggplot(mapping = aes(x = position, 
                       y = base_salary, 
                       color = club)) + 
  geom_jitter(size = 2.5) + 
  scale_y_continuous(labels=scales::dollar_format()) + 
    scale_color_discrete( 
    labels = c("CHI" = "Chicago Fire", "CHV" = "Chivas USA", "CLB" = "Columbus Crew", "COL" =         "Colorado Rapids", "DAL" = "FC Dallas", "DC" = "D.C. United", "HOU" = "Houston Dynamo", "KC" =     "Kansas City Wizards", "LA" = "LA Galaxy", "NE" = "New England Revolution", "NY" = "New York Red Bulls", "RSL" = "Real Salt Lake", "TFC" = "Toronto FC")) + 
  labs(title = "Soccer salaries earned for midfielders in 2007",
       subtitle = "Average salary for midfielders is $127,843, which is more than average for defense",
       x = "Position", 
       y = "Player Base Salary", 
       caption = "Source: Originally from MLS Union", 
       color = "Club") + 
  theme_classic() + 
  geom_hline(yintercept = 127843.4	, linetype = "dashed", color = "red")
```
This data shows the spread of salaries for midfielders in 2007. The colors show the clubs each player was in. There are a couple extreme outliers in this graph, which show that there isn't consistency for midfielder salaries. The line in the middle of the graph displays the average for all forwards in the MLS League in 2007, which is $127,843. 




