---
title: "Models"
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(readxl)
library(writexl)
library(stringr)
library(rstanarm)
library(dplyr)
library(gtsummary)
```



```{r}
#| echo: false
#| message: false
#| warning: false
mls_data <- read.csv("mls-salaries-2007.csv")

```

## What is the approximate salary of a player based on their field position? 






### Model Equation

$$y_i = \beta_0  + \beta_1 x_{1,i} + \epsilon_i$$

with $y = base\_salary$, $x_1 = position$, and $\epsilon_i \sim N(0, \sigma^2)$.









### Fitted Model
```{r}
#| echo: false
#| message: false
#| warning: false
x<- mls_data |> 
  select(base_salary, position, club)

fit_obj <- stan_glm(formula = base_salary ~ position,
                    family = gaussian,
                    data = x,
                    refresh = 0,
                    seed = 9)
fit_obj
```


```{r}
#| echo: false
#| message: false
#| warning: false
newobs <- tibble(position = "F")

pe <- posterior_epred(fit_obj, newdata = newobs) |> 
  as_tibble() 
```

### Plot
```{r}
#| echo: false
#| message: false
#| warning: false
pe |> 
  ggplot(aes(x = `1`)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 100)  +
    labs(title = "Posterior for Expected Salary",
         subtitle = "A forward earns around 150,000",
         x = "Forward Position",
         y = "Probability", 
         caption = "Source: Originally from MLS Union") +
    scale_x_continuous(labels = scales::dollar_format()) +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic()
```


```{r}
#| echo: false
#| message: false
#| warning: false
newobs <- tibble(position = "M")

pm <- posterior_epred(fit_obj, newdata = newobs) |> 
  as_tibble() 
```

 
```{r}
#| echo: false
#| message: false
#| warning: false
pm |> 
  ggplot(aes(x = `1`)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 100)  +
    labs(title = "Posterior for Expected Salary",
         subtitle = "A midfielder earns around 130,000",
         x = "Midfield Position",
         y = "Probability", 
         caption = "Source: Originally from MLS Union") +
    scale_x_continuous(labels = scales::dollar_format()) +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic()
```




```{r}
#| echo: false
#| message: false
#| warning: false
newobs <- tibble(position = "D")

pd <- posterior_epred(fit_obj, newdata = newobs) |> 
  as_tibble() 
```

 
```{r}
#| echo: false
#| message: false
#| warning: false
pd |> 
  ggplot(aes(x = `1`)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 100)  +
    labs(title = "Posterior for Expected Salary",
         subtitle = "A defender earns around 75,000",
         x = "Defense Position",
         y = "Probability", 
         caption = "Source: Originally from MLS Union") +
    scale_x_continuous(labels = scales::dollar_format()) +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic()
```



```{r}
#| echo: false
#| message: false
#| warning: false
newobs <- tibble(position = "GK")

pe <- posterior_epred(fit_obj, newdata = newobs) |> 
  as_tibble() 
```

 
```{r}
#| echo: false
#| message: false
#| warning: false
pe |> 
  ggplot(aes(x = `1`)) +
    geom_histogram(aes(y = after_stat(count/sum(count))),
                   bins = 100)  +
    labs(title = "Posterior for Expected Salary",
         subtitle = "A goalkeeper earns around 70,000",
         x = "GoalKeeper Position",
         y = "Probability", 
         caption = "Source: Originally from MLS Union") +
    scale_x_continuous(labels = scales::dollar_format()) +
    scale_y_continuous(labels = scales::percent_format()) +
    theme_classic()
```






