---
title: "Offense"
editor: visual
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(readxl)
library(writexl)
library(stringr)
library(rstanarm)
library(dplyr)
```

```{r}
#| echo: false
#| message: false
#| warning: false

# puts the data into a spreadsheet
fdata <- read.csv("mls-salaries-2007.csv")

```

### Plot for all forwards in MLS League in 2007

```{r}
#| echo: false
#| message: false
#| warning: false

# plots the data by filtering the position to be forwards
# points are colored by club name
# plots a dotted line to represent the average salary for a forwards
fdata |> 
  filter(position == "F") |> 
  select(position, base_salary, club, first_name, last_name) |>
  ggplot(mapping = aes(x = position, 
                       y = base_salary, 
                       color = club)) + 
  geom_jitter(size = 2.5) + 
  scale_y_continuous(labels=scales::dollar_format()) + 
    scale_color_discrete( 
    labels = c("CHI" = "Chicago Fire", "CHV" = "Chivas USA", "CLB" = "Columbus Crew", "COL" =         "Colorado Rapids", "DAL" = "FC Dallas", "DC" = "D.C. United", "HOU" = "Houston Dynamo", "KC" =     "Kansas City Wizards", "LA" = "LA Galaxy", "NE" = "New England Revolution", "NY" = "New York Red Bulls", "RSL" = "Real Salt Lake", "TFC" = "Toronto FC")) + 
  labs(title = "Soccer salaries earned for forwards in 2007",
       subtitle = "Average for forwards is $147,653, more than average for all positions", 
       x = "Position", 
       y = "Player Base Salary", 
       caption = "Source: Originally from MLS Union", 
       color = "Club") + 
  theme_classic() + 
  geom_hline(yintercept = 147653, linetype = "dashed", color = "blue")
```

This data shows the spread of salaries for forwards in 2007. The colors show the clubs each player was in. There are a few outliers in this graph, which show that there isn't consistency for forwards salaries. The line in the middle of the graph displays the average for all forwards in the MLS League in 2007, which is \$147,653.
